language: r
r: bioc-release
cache: packages

r_packages:
  - covr

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

r_check_args:  --no-vignettes --timings

after_success:
   - travis_wait Rscript -e 'library(covr); codecov()'
