language: r
r: bioc-release
cache: packages

r_packages:
  - covr

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

# currently too slow    
# after_success:
#   - Rscript -e 'library(covr); codecov()'
